[controls]
selected_type = 'Keyboard'

[controls.keyboard_map]
Up = ['W']
Select = ['K']
A = ['Space']
Start = ['Return']
Left = ['A']
B = ['LShift']
Right = ['D']
Down = ['S']

[color_palette]
color1 = [
    8,
    24,
    32,
]
color2 = [
    52,
    104,
    86,
]
color3 = [
    136,
    192,
    112,
]
color4 = [
    224,
    248,
    208,
]
